#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class Lookup
  include ::Thrift::Struct, ::Thrift::Struct_Union
  BUCKET = 1
  KEY = 2

  FIELDS = {
    BUCKET => {:type => ::Thrift::Types::STRING, :name => 'bucket'},
    KEY => {:type => ::Thrift::Types::STRING, :name => 'key'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class InvalidKey < ::Thrift::Exception
  include ::Thrift::Struct, ::Thrift::Struct_Union
  def initialize(message=nil)
    super()
    self.error = message
  end

  def message; error end

  ERROR = 1

  FIELDS = {
    ERROR => {:type => ::Thrift::Types::STRING, :name => 'error'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

